import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'authorization, x-client-info, apikey, content-type','access-control-allow-methods':'POST, OPTIONS'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'content-type':'application/json'}});
const service=()=>createClient(Deno.env.get('SUPABASE_URL')||'',Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'');
const anon=()=>createClient(Deno.env.get('SUPABASE_URL')||'',Deno.env.get('SUPABASE_ANON_KEY')||'');
async function currentUser(req:Request){const auth=req.headers.get('authorization')||'';if(!auth.startsWith('Bearer '))return null;const {data,error}=await anon().auth.getUser(auth.slice(7));return error?null:data.user}
async function isAdmin(db:any,userId:string){const [{data:access},{data:roles}]=await Promise.all([db.from('app_user_access').select('status,must_change_password').eq('user_id',userId).maybeSingle(),db.from('user_roles').select('role').eq('user_id',userId)]);return access?.status==='Active'&&access?.must_change_password!==true&&(roles||[]).some((row:any)=>row.role==='Admin')}
async function settings(db:any){const {data,error}=await db.from('operations_notification_settings').select('*').eq('id',1).single();if(error)throw error;return data}
const minutes=(value:unknown)=>{const [h,m]=String(value||'00:00').split(':').map(Number);return h*60+m};
const validTime=(value:unknown)=>{const s=String(value||'');if(/^([01]\d|2[0-3]):[0-5]\d$/.test(s))return `${s}:00`;if(/^([01]\d|2[0-3]):[0-5]\d:[0-5]\d$/.test(s))return s;return null};
const integer=(value:unknown,min:number,max:number,fallback:number)=>{const n=Number(value);return Number.isInteger(n)&&n>=min&&n<=max?n:fallback};
async function updateSettings(db:any,body:Record<string,unknown>,userId:string){const old=await settings(db);const patch:any={notifications_enabled:body.notifications_enabled===true,task_push_enabled:body.task_push_enabled===true,assignment_push_enabled:body.assignment_push_enabled!==false,assignment_delay_minutes:integer(body.assignment_delay_minutes,0,1440,old.assignment_delay_minutes),due_soon_enabled:body.due_soon_enabled!==false,due_soon_hours_before:integer(body.due_soon_hours_before,1,720,old.due_soon_hours_before),overdue_enabled:body.overdue_enabled!==false,overdue_repeat_days:integer(body.overdue_repeat_days,1,30,old.overdue_repeat_days),admin_weekly_email_enabled:body.admin_weekly_email_enabled===true,admin_weekly_day:integer(body.admin_weekly_day,1,7,old.admin_weekly_day),employee_weekly_email_allowed:body.employee_weekly_email_allowed===true,employee_weekly_day:integer(body.employee_weekly_day,1,7,old.employee_weekly_day),push_days:Array.isArray(body.push_days)?[...new Set((body.push_days as unknown[]).map(Number).filter(n=>Number.isInteger(n)&&n>=1&&n<=7))]:old.push_days,updated_at:new Date().toISOString(),updated_by:userId};for(const key of ['due_soon_send_time','overdue_send_time','push_start_time','push_end_time','admin_weekly_time','employee_weekly_time']){const time=validTime(body[key]);if(time)patch[key]=time}if(!patch.push_days.length)throw new Error('Choose at least one push delivery day.');if(minutes(patch.push_start_time||old.push_start_time)>=minutes(patch.push_end_time||old.push_end_time))throw new Error('Push end time must be later than push start time.');const {data,error}=await db.from('operations_notification_settings').update(patch).eq('id',1).select('*').single();if(error)throw error;return data}
async function adminStatus(db:any){const current=await settings(db);const [{count:devices},{count:users},{count:failures},{data:last}]=await Promise.all([db.from('operations_push_subscriptions').select('*',{count:'exact',head:true}).eq('permission_state','granted'),db.from('operations_notification_preferences').select('*',{count:'exact',head:true}).eq('push_enabled',true),db.from('operations_notification_deliveries').select('*',{count:'exact',head:true}).eq('status','failed'),db.from('operations_notification_deliveries').select('attempted_at,status').order('attempted_at',{ascending:false}).limit(1)]);return{settings:current,enrolment:{granted_devices:devices||0,push_enabled_users:users||0},recent_failures:failures||0,last_delivery:last?.[0]||null,backend:{task_push_delivery_enabled:Deno.env.get('TASK_PUSH_DELIVERY_ENABLED')==='true',weekly_delivery_enabled:Deno.env.get('WEEKLY_ROUTINE_DELIVERY_ENABLED')==='true'}}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'POST required'},405);const body=await req.json().catch(()=>null) as Record<string,unknown>|null;const db=service();try{const user=await currentUser(req);if(!user)return json({error:'Unauthenticated'},401);if(!await isAdmin(db,user.id))return json({error:'Admin access required'},403);const action=String(body?.action||'');if(action==='admin_notification_status')return json({ok:true,...await adminStatus(db)});if(action==='update_admin_notification_settings')return json({ok:true,settings:await updateSettings(db,body||{},user.id)});return json({error:'Unknown action'},400)}catch(error){return json({error:error instanceof Error?error.message:'Notification control failed.'},500)}});